### ISSUE TITLE
Misunderstanding in ethereum.txt

### ISSUE THREAD

**Issue by ToheartZhang** [vatsalpatels/Graph-DL-Based-Anomaly-Detection-in-Ethereum#1]
Could you provide descriptions of each field in ethereum.txt? Thx.

**Comment by vatsalpatels** [comment]
> Could you provide descriptions of each field in ethereum.txt? Thx.

Hi Jason,

You can find a detailed description of each field in the below paper -

https://link.springer.com/chapter/10.1007/978-3-030-65745-1_8

Best,
Vatsal
